Fix: RichTextEditor.tsx style error
The error `src/components/Editor/RichTextEditor.tsx(180,14): error TS2322: Type '{ children: string; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'. Property 'jsx' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'` indicates a type mismatch in the `style jsx` block. This commit addresses the error.